apiVersion: v1
kind: Service
metadata:
  name: salt
  labels:
    app: salt
spec:
  type: ClusterIP
  ports:
  - port: 4505
    protocol: TCP
    targetPort: publish
    name: publish
  - port: 4506
    protocol: TCP
    targetPort: request
    name: request
  selector:
    app: salt-master
